"""empty message

Revision ID: cf6ba48b3e7b
Revises: cccf1c4ea739
Create Date: 2018-04-27 04:40:30.941448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6ba48b3e7b'
down_revision = 'cccf1c4ea739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
